Repository kreativision/mtrace-server, pull requests merged in 2023-01, with the labels that each got.

#2 Starter boilerplate and docs
  .vscode/settings.json
  Readme.md
  nodemon.json
  package-lock.json
  package.json
  src/config/db.ts
  src/constants/app.constants.ts
  src/controllers/user.controller.ts
  src/index.ts
  src/middlewares/auth.middleware.ts
  src/middlewares/error.middleware.ts
  src/models/user.model.ts
  src/routes/user.routes.ts
  src/types/category.ts
  src/types/requests.ts
  src/types/user.ts
  tsconfig.json
Labels: documentation, feature

#3 Decouple Application code from runner code.
  .vscode/settings.json
  dev.ts
  nodemon.json
  package-lock.json
  package.json
  prod.js
  src/config/db.ts
  src/config/mongoose.ts
  src/constants/app.constants.ts
  src/controllers/user.controller.ts
  src/index.ts
  src/middlewares/auth.middleware.ts
  src/middlewares/error.middleware.ts
  src/models/user.model.ts
  src/routes/user.routes.ts
  src/types/user.ts
  tsconfig.json
Labels: documentation, enhancement, feature

#6 Created Expense, Budget and ExpensePlan models and boilerplate code
  src/constants/app.constants.ts
  src/controllers/budget.controller.ts
  src/controllers/expense.controller.ts
  src/controllers/expensePlan.controller.ts
  src/index.ts
  src/models/budget.model.ts
  src/models/category.model.ts
  src/models/expense.model.ts
  src/models/expensePlan.model.ts
  src/models/user.model.ts
  src/routes/budget.routes.ts
  src/routes/expense.routes.ts
  src/routes/expensePlan.routes.ts
  src/types/budget.ts
  src/types/category.ts
  src/types/expense.ts
  src/types/expensePlan.ts
Labels: enhancement, feature
